CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLES VARCHAR(255) NOT NULL DEFAULT 'USER'
);